### ISSUE TITLE
Error (SystemJS) Cannot read property push of 'undefined' for loader._extensions

### ISSUE THREAD

**Issue by gdyrrahitis** [stealjs/system-json#4]
I am getting this error when trying to use the json plugin for SystemJS.

```
Error: (SystemJS) Cannot read property 'push' of undefined
    TypeError: Cannot read property 'push' of undefined
        at _SYSTEM_addJSON (http://localhost:3000/node_modules/system-json/json.js:12:20)
        at eval (http://localhost:3000/node_modules/system-json/json.js:83:2)
    Evaluating http://localhost:3000/node_modules/system-json/json.js
    Error loading http://localhost:3000/node_modules/system-json/json.js
```

It has to do with this line from `json.js`:

```
// Add the extension to _extensions so that it can be cloned.
loader._extensions.push(_SYSTEM_addJSON);
```

Apparently, the _extensions property is undefined when loading the `json.js`. I can make this go away by conditionally checking if it is undefined

```
// Add the extension to _extensions so that it can be cloned.
if(loader._extensions)
    loader._extensions.push(_SYSTEM_addJSON);
```

My code for systemsjs-config.js

```
(function () {
    var map = {
        "app": "src",
        "angular": "node_modules/angular",
        "ngSanitize": "node_modules/angular-sanitize",
        "ngRoute": "node_modules/angular-route",
        "ngStorage": "node_modules/ngstorage/",
        "json": "node_modules/system-json/"
    };

    var packages = {
        "app": { main: "main.js", defaultExtension: "js" },
        "angular": { main: "index.js", defaultExtension: "js" },
        "ngSanitize": { main: "index.js", defaultExtension: "js" },
        "ngRoute": { main: "index.js", defaultExtension: "js" },
        "ngStorage": { main: "ngStorage.min.js", defaultExtension: "js" },
        "json": { main: "json.js", defaultExtension: "js" }
    };

    var config = {
        map: map,
        packages: packages
    };
    System.config(config);
})();
```

 And on my index.html

```
<!DOCTYPE html>
<html lang="en" ng-app="app">

<head>
    <title>Application</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet">

    <!--Module loader-->
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="systemjs-config.js"></script>
    <script>
        System.import("json").then(function() {
            return System.import("app").catch(function(err) { console.log(err); });
        }).then(null, function(err){
            console.error("Oh no, error!", err);
        });
    </script>
</head>

<body>
    <ng-view></ng-view>
</body>

</html>
```

Should I rely to this workaround for now? It seems it is working fine without it. What's the purpose of this line?

**Comment by matthewp** [comment]
This extension is for an older version of Systemjs. There are probably other extensions for newer versions.
